language: node_js
node_js:
  - '4.6.1'
  - 'node'
os:
  - linux
before_script:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g coveralls
after_script:
  - npm run coverage
  - npm run coveralls
